language: objective-c
osx_image: xcode10.2
script:
- set -o pipefail
- bundle exec danger || echo "Danger failed, moving on"
- brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
- brew install xcbeautify
- xcodebuild test -project FontAwesome.xcodeproj -scheme FontAwesome -destination 'platform=iOS Simulator,name=iPhone XS' | xcbeautify
- xcodebuild -project FontAwesome.xcodeproj -scheme FontAwesome-watchOS -destination 'platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm' | xcbeautify
- xcodebuild -project FontAwesome.xcodeproj -scheme FontAwesome-tvOS -destination 'platform=tvOS Simulator,name=Apple TV' | xcbeautify
before_deploy:
  - carthage build --no-skip-current
  - carthage archive FontAwesome
deploy:
  provider: releases
  api_key:
    secure: cas9AI0zCDIumfTKk79sazU6PLuVXICET6eIjqivntG1Qs1g9yvmsI3JbBMLPyZqDl0w+uDHhki7cBeO3tDXJ8cxIErj8xYwtX4TMnA916QWqo7DVkGjkqAxosWWBGBgx6VbcSw0WSnPYrlo41c5yKssuDal+CZjoTeadJqB8Rg=
  file: FontAwesome.framework.zip
  skip_cleanup: true
  on:
    tags: true
    repo: thii/FontAwesome.swift
notifications:
  email: false
